USE [master]
GO
CREATE DATABASE [ChadDB];
GO
ALTER DATABASE [ChadDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ChadDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ChadDB] SET ANSI_NULL_DEFAULT ON 
GO
ALTER DATABASE [ChadDB] SET ANSI_NULLS ON 
GO
ALTER DATABASE [ChadDB] SET ANSI_PADDING ON 
GO
ALTER DATABASE [ChadDB] SET ANSI_WARNINGS ON 
GO
ALTER DATABASE [ChadDB] SET ARITHABORT ON 
GO
ALTER DATABASE [ChadDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ChadDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ChadDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ChadDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ChadDB] SET CURSOR_DEFAULT  LOCAL 
GO
ALTER DATABASE [ChadDB] SET CONCAT_NULL_YIELDS_NULL ON 
GO
ALTER DATABASE [ChadDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ChadDB] SET QUOTED_IDENTIFIER ON 
GO
ALTER DATABASE [ChadDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ChadDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ChadDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ChadDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ChadDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ChadDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ChadDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ChadDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ChadDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ChadDB] SET RECOVERY FULL 
GO
ALTER DATABASE [ChadDB] SET  MULTI_USER 
GO
ALTER DATABASE [ChadDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ChadDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ChadDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ChadDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ChadDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ChadDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [ChadDB] SET QUERY_STORE = OFF
GO
USE [ChadDB]
GO
/****** Object:  Table [dbo].[Bolgeler]    Script Date: 4.01.2026 14:47:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Bolgeler](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Isim] [nvarchar](50) NOT NULL,
	[Hakkinda] [nvarchar](max) NOT NULL,
	[SehirId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Nufus]    Script Date: 4.01.2026 14:47:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Nufus](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[SehirId] [int] NOT NULL,
	[Yil] [int] NOT NULL,
	[NufusMiktar] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ResimlerSlider]    Script Date: 4.01.2026 14:47:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ResimlerSlider](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ResimUrl] [nvarchar](250) NOT NULL,
	[Baslik] [nvarchar](100) NULL,
	[Aciklama] [nvarchar](250) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Sehirler]    Script Date: 4.01.2026 14:47:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Sehirler](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Isim] [nvarchar](50) NOT NULL,
	[Nufus] [int] NOT NULL,
	[Hakkinda] [nvarchar](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[Bolgeler]  WITH CHECK ADD FOREIGN KEY([SehirId])
REFERENCES [dbo].[Sehirler] ([Id])
GO
ALTER TABLE [dbo].[Nufus]  WITH CHECK ADD FOREIGN KEY([SehirId])
REFERENCES [dbo].[Sehirler] ([Id])
GO
USE [master]
GO
ALTER DATABASE [ChadDB] SET  READ_WRITE 
GO
