//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdevD1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Bolgeler
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Bölge adý boþ býrakýlamaz")]
        [Display(Name="Bölge Ýsmi")]
        public string Isim { get; set; }

        [StringLength(500, ErrorMessage = "Hakkýnda alaný en fazla 500 karakter olabilir")]
        [Display(Name ="Hakkýnda")]
        public string Hakkinda { get; set; }

        [Required(ErrorMessage = "Þehir seçilmelidir")]
        [Display(Name ="Þehir")]
        public int SehirId { get; set; }
    
        public virtual Sehirler Sehirler { get; set; }
    }
}
