//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdevD1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.CompilerServices;

    public partial class Nufus
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Þehir seçilmelidir")]
        [Display(Name = "Þehir Ýsmi")]
        public int SehirId { get; set; }

        [Required(ErrorMessage = "Yýl boþ býrakýlamaz")]
        [Range(1800, 2100, ErrorMessage = "Yýl 1800 ile 2100 arasýnda olmalýdýr")]
        [Display(Name ="Yýl")]
        public int Yil { get; set; }

        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "Nüfus miktarý 0'dan büyük olmalýdýr")]
        [Display(Name ="Nüfus Miktarý")]
        public int NufusMiktar { get; set; }
    
        public virtual Sehirler Sehirler { get; set; }
    }
}
