//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdevD1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations; 

    public partial class Sehirler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sehirler()
        {
            this.Bolgelers = new HashSet<Bolgeler>();
            this.Nufus1 = new HashSet<Nufus>();
        }
    
        public int Id { get; set; }

        [Required(ErrorMessage = "Þehir adý boþ býrakýlamaz")]
        [Display(Name ="Þehir Ýsmi")]
        public string Isim { get; set; }

        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "Nüfus 0'dan büyük olmalýdýr")]
        [Display(Name = "Nüfus")]
        public int Nufus { get; set; }

        [Display(Name = "Hakkýnda")]
        public string Hakkinda { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bolgeler> Bolgelers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nufus> Nufus1 { get; set; }
    }
}
